repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.11
    hooks:
      - id: ruff-check
        name: ruff-lint
        args:
          - --output-format=github

      - id: ruff-format
        name: ruff-format
        args:
          - --check

  # swithc to ty after release
  # https://github.com/astral-sh/ty/issues/269
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        name: mypy
